### ISSUE TITLE
socket部分设计

### ISSUE THREAD

**Issue by findstr** [chng/multichat#1]
为什么要采用udp协议呢
为什么要不使用epoll呢

**Comment by chng** [comment]
udp轮询保持会话。下一步用epoll和非阻塞的socket，写成同步非阻塞的方式。

**Comment by findstr** [comment]
我觉得你应该用将epoll部分采用异步封装的手法抽象成为一个gate模块, 将socket数据部分剥离出来， 以便你可以专心写业务逻辑

**Comment by chng** [comment]
有道理，封装部分容我想想，必须写成重用性很高的类。
